version: '3'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dynamicform

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "3030:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
